spring.application.name=CycleCare

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true

server.servlet.session.timeout=45m
server.error.whitelabel.enabled=false

cyclecare.security.remember-me-key=8f2c7a1d93b6e5f4a8c1d7e2b9f6a3c5